# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.

# samples : list of genomes for analysis of bgcflow with multiple sources mentioned as below
samples: config/samples.csv

# prokka-db : list of the custom accessions to use as prokka genus database
prokka-db: config/prokka-db.csv